### ISSUE TITLE
Fatal error: Class 'ArchiveFolder_Ingester_Alto'

### ISSUE THREAD

**Issue by JBPressac** [Daniel-KM/ArchiveFolder#2]
Hello,
Thank you for the previous bug fix. I have another error with ArchiveFolder version 2.4 on Omeka 2.3.1 trying to add the example archive folder (Folder_Test), the following error is displayed: 

Fatal error: Class 'ArchiveFolder_Ingester_Alto' not found in /var/www/omeka/plugins/ArchiveFolder/libraries/ArchiveFolder/Mapping/Mets.php on line 217

Seems another library is missing ?
Thanks,

**Comment by Daniel-KM** [comment]
Hi,

This is a similar issue, that I fixed with the last master version. To import Alto, you need the plugin <a href="https://github.com/Daniel-KM/OcrElementSet">Ocr Element Set</a> (and the good Alto version). The new release 2.5 is ok (or master).

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
